import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1786978325132 implements MigrationInterface {
    name = 'Init1786978325132'

    public async up(queryRunner: QueryRunner): Promise<void> {
        // 수동 추가(생성기가 넣어주지 않음): refresh_tokens.id 의 DEFAULT uuid_generate_v4() 가
        // 이 확장을 요구한다. TypeORM 드라이버가 접속 시 자동 설치해 주지만, 그 동작에 의존하면
        // SQL 직접 적용/확장 설치 권한 없는 계정에서 조용히 깨진다 → 마이그레이션을 자기완결적으로 둔다.
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
        await queryRunner.query(`CREATE TABLE "wish_list_items" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "user_id" integer NOT NULL, "product_id" integer NOT NULL, CONSTRAINT "UQ_acee9756d5d218e351c24b86ccb" UNIQUE ("user_id", "product_id"), CONSTRAINT "PK_e623d313868fb14294289b208e1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a42daf2938b2aeec8ad000a9e4" ON "wish_list_items" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."roles_name_enum" AS ENUM('buyer', 'seller', 'admin')`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" "public"."roles_name_enum" NOT NULL, CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "email" character varying NOT NULL, "password" character varying NOT NULL, "nickName" character varying NOT NULL, "phoneNumber" character varying NOT NULL, "address" character varying NOT NULL, "isEmailVerified" boolean NOT NULL DEFAULT false, "is_demo" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."settlements_status_enum" AS ENUM('pending', 'confirmed', 'paid')`);
        await queryRunner.query(`CREATE TABLE "settlements" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "order_id" integer NOT NULL, "seller_id" integer NOT NULL, "order_number" character varying NOT NULL, "amount" numeric(12,2) NOT NULL, "commission_rate" numeric(5,2) NOT NULL DEFAULT '10', "commission_amount" numeric(12,2) NOT NULL, "settlement_amount" numeric(12,2) NOT NULL, "status" "public"."settlements_status_enum" NOT NULL DEFAULT 'pending', "confirmed_at" TIMESTAMP WITH TIME ZONE, "paid_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_b50d1630969c247659e4af17792" UNIQUE ("order_id", "seller_id"), CONSTRAINT "PK_5f523ce152b84e818bff9467aab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2a6aecc322b9c89e6b8f2c5834" ON "settlements" ("order_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_52e93e1b93923907c5493ea202" ON "settlements" ("seller_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_068dd3735fbbc98234abb78375" ON "settlements" ("order_number") `);
        await queryRunner.query(`CREATE TYPE "public"."sellers_status_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "sellers" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "user_id" integer NOT NULL, "businessName" character varying NOT NULL, "businessNumber" character varying NOT NULL, "representativeName" character varying NOT NULL, "businessAddress" character varying NOT NULL, "contactEmail" character varying, "contactPhone" character varying, "bankName" character varying NOT NULL, "bankAccountNumber" character varying NOT NULL, "bankAccountHolder" character varying NOT NULL, "status" "public"."sellers_status_enum" NOT NULL DEFAULT 'pending', "rejectionReason" text, "approvedAt" TIMESTAMP, CONSTRAINT "UQ_5f5238d4317872f55df2d299bc0" UNIQUE ("businessNumber"), CONSTRAINT "REL_83f4670f0e114d0be3731bade8" UNIQUE ("user_id"), CONSTRAINT "PK_97337ccbf692c58e6c7682de8a2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reviews" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "user_id" integer NOT NULL, "product_id" integer NOT NULL, "order_id" integer NOT NULL, "rating" smallint NOT NULL, "comment" text NOT NULL, "imageUrls" text array NOT NULL DEFAULT '{}', CONSTRAINT "UQ_b3207798e33cd8099ea7f0ec4ff" UNIQUE ("user_id", "product_id", "order_id"), CONSTRAINT "PK_231ae565c273ee700b283f15c1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_728447781a30bc3fcfe5c2f1cd" ON "reviews" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9482e9567d8dcc2bc615981ef4" ON "reviews" ("product_id") `);
        await queryRunner.query(`CREATE TABLE "product_images" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "url" character varying NOT NULL, "isPrimary" boolean NOT NULL DEFAULT false, "sortOrder" integer NOT NULL DEFAULT '0', "productId" integer, CONSTRAINT "PK_1974264ea7265989af8392f63a1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."products_status_enum" AS ENUM('draft', 'published', 'sold_out', 'hidden', 'discontinued')`);
        await queryRunner.query(`CREATE TYPE "public"."products_approval_status_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TYPE "public"."products_sales_type_enum" AS ENUM('normal', 'pre_order', 'group_buy')`);
        await queryRunner.query(`CREATE TABLE "products" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "description" text NOT NULL, "price" numeric(10,2) NOT NULL, "brand" character varying NOT NULL, "stockQuantity" integer NOT NULL DEFAULT '0', "status" "public"."products_status_enum" NOT NULL DEFAULT 'draft', "approval_status" "public"."products_approval_status_enum" NOT NULL DEFAULT 'pending', "sales_type" "public"."products_sales_type_enum" NOT NULL DEFAULT 'normal', "rejection_reason" text, "approved_at" TIMESTAMP, "salesCount" integer NOT NULL DEFAULT '0', "viewCount" integer NOT NULL DEFAULT '0', "isEvent" boolean NOT NULL, "discountRate" integer, "rating" numeric(3,1), "specs" jsonb NOT NULL DEFAULT '{}', "seller_id" integer, "category_id" integer, "reviewCount" integer NOT NULL DEFAULT '0', "ratingSum" integer NOT NULL DEFAULT '0', "wishCount" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tags" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, CONSTRAINT "UQ_d90243459a697eadb8ad56e9092" UNIQUE ("name"), CONSTRAINT "PK_e7dc17249a1148a1970748eda99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."product_summaries_status_enum" AS ENUM('fresh', 'stale', 'generating')`);
        await queryRunner.query(`CREATE TABLE "product_summaries" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "productId" integer NOT NULL, "summaryText" text, "status" "public"."product_summaries_status_enum" NOT NULL DEFAULT 'stale', "reviewCountAtGen" integer NOT NULL DEFAULT '0', "model" character varying(100), "promptVersion" integer NOT NULL DEFAULT '0', "generatedAt" TIMESTAMP WITH TIME ZONE, "lockedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "REL_d05219e764bbdf7037198e26b9" UNIQUE ("productId"), CONSTRAINT "PK_a5a7cd1e6cd2c73b5d7c0fc27fb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d05219e764bbdf7037198e26b9" ON "product_summaries" ("productId") `);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "order_id" integer NOT NULL, "product_id" integer NOT NULL, "seller_id" integer, "product_name" character varying NOT NULL, "product_price" numeric(10,2) NOT NULL, "product_image_url" text, "quantity" integer NOT NULL, "subtotal" numeric(12,2) NOT NULL, CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."shipments_status_enum" AS ENUM('preparing', 'shipped', 'delivered')`);
        await queryRunner.query(`CREATE TABLE "shipments" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "order_id" integer NOT NULL, "seller_id" integer NOT NULL, "status" "public"."shipments_status_enum" NOT NULL DEFAULT 'preparing', "tracking_number" character varying(50), "carrier" character varying, "shipped_at" TIMESTAMP WITH TIME ZONE, "delivered_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_d86b4c4f47492549d4bbb6f2b4f" UNIQUE ("order_id", "seller_id"), CONSTRAINT "PK_6deda4532ac542a93eab214b564" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum" AS ENUM('pending_payment', 'paid', 'preparing', 'shipped', 'delivered', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "order_number" character varying NOT NULL, "user_id" integer NOT NULL, "status" "public"."orders_status_enum" NOT NULL DEFAULT 'pending_payment', "total_amount" numeric(12,2) NOT NULL, "shipping_address" text NOT NULL, "recipient_name" character varying NOT NULL, "recipient_phone" character varying NOT NULL, "memo" text, "paid_at" TIMESTAMP WITH TIME ZONE, "cancelled_at" TIMESTAMP WITH TIME ZONE, "cancellation_reason" text, "shipped_at" TIMESTAMP WITH TIME ZONE, "delivered_at" TIMESTAMP WITH TIME ZONE, "completed_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_75eba1c6b1a66b09f2a97e6927b" UNIQUE ("order_number"), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_75eba1c6b1a66b09f2a97e6927" ON "orders" ("order_number") `);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('ready', 'paid', 'cancelled', 'partial_cancelled', 'failed')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "order_id" integer NOT NULL, "imp_uid" character varying, "merchant_uid" character varying NOT NULL, "payment_method" character varying, "amount" numeric(12,2) NOT NULL, "status" "public"."payments_status_enum" NOT NULL DEFAULT 'ready', "pg_provider" character varying, "receipt_url" text, "paid_at" TIMESTAMP WITH TIME ZONE, "cancelled_at" TIMESTAMP WITH TIME ZONE, "cancel_amount" numeric(12,2) NOT NULL DEFAULT '0', "cancel_reason" text, "raw_response" jsonb, CONSTRAINT "UQ_b2f7b823a21562eeca20e72b006" UNIQUE ("order_id"), CONSTRAINT "UQ_86f2b15ca0fd4f9a7eaae75fe6b" UNIQUE ("imp_uid"), CONSTRAINT "UQ_11b604779919afa0aca3556c636" UNIQUE ("merchant_uid"), CONSTRAINT "REL_b2f7b823a21562eeca20e72b00" UNIQUE ("order_id"), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_86f2b15ca0fd4f9a7eaae75fe6" ON "payments" ("imp_uid") `);
        await queryRunner.query(`CREATE INDEX "IDX_11b604779919afa0aca3556c63" ON "payments" ("merchant_uid") `);
        await queryRunner.query(`CREATE TYPE "public"."inquiries_status_enum" AS ENUM('waiting', 'answered')`);
        await queryRunner.query(`CREATE TABLE "inquiries" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "user_id" integer NOT NULL, "product_id" integer NOT NULL, "seller_id" integer NOT NULL, "title" character varying(200) NOT NULL, "content" text NOT NULL, "answer" text, "answered_at" TIMESTAMP WITH TIME ZONE, "is_secret" boolean NOT NULL DEFAULT false, "status" "public"."inquiries_status_enum" NOT NULL DEFAULT 'waiting', CONSTRAINT "PK_ceacaa439988b25eb9459e694d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a896a1864d60d5707403e0a081" ON "inquiries" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fdb6fc620f190e9d51cb2c6a58" ON "inquiries" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c860a531fd90a7697efabf4efa" ON "inquiries" ("seller_id") `);
        await queryRunner.query(`CREATE TABLE "categories" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "parent_id" integer, "path" character varying(500) NOT NULL DEFAULT '/', "depth" integer NOT NULL DEFAULT '0', "sort_order" integer NOT NULL DEFAULT '0', "is_visible" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_420d9f679d41281f282f5bc7d09" UNIQUE ("slug"), CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_420d9f679d41281f282f5bc7d0" ON "categories" ("slug") `);
        await queryRunner.query(`CREATE TABLE "cart_items" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "cart_id" integer NOT NULL, "product_id" integer NOT NULL, "quantity" integer NOT NULL DEFAULT '1', CONSTRAINT "UQ_dba960dbfd8636893d3c7acb18d" UNIQUE ("cart_id", "product_id"), CONSTRAINT "PK_6fccf5ec03c172d27a28a82928b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "carts" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "user_id" integer NOT NULL, CONSTRAINT "UQ_2ec1c94a977b940d85a4f498aea" UNIQUE ("user_id"), CONSTRAINT "REL_2ec1c94a977b940d85a4f498ae" UNIQUE ("user_id"), CONSTRAINT "PK_b5f695a59f5ebb50af3c8160816" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" integer NOT NULL, "tokenHash" character varying(500) NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "isRevoked" boolean NOT NULL DEFAULT false, "revokedAt" TIMESTAMP, "userAgent" character varying, "ipAddress" character varying, "deviceId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "lastUsedAt" TIMESTAMP, "isPersistent" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_610102b60fea1455310ccd299d" ON "refresh_tokens" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_56b91d98f71e3d1b649ed6e9f3" ON "refresh_tokens" ("expiresAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_e59cfb4ce9deac3c9411eaa0e0" ON "refresh_tokens" ("userId", "isRevoked") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" SERIAL NOT NULL, "userId" integer, "action" character varying(50) NOT NULL, "ipAddress" character varying NOT NULL, "userAgent" character varying, "metadata" json, "success" boolean NOT NULL DEFAULT true, "errorMessage" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0ec936941eb8556fcd7a1f0eae" ON "audit_logs" ("action", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_99e589da8f9e9326ee0d01a028" ON "audit_logs" ("userId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "assistant_messages" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "conversationId" integer NOT NULL, "role" character varying(16) NOT NULL, "content" text NOT NULL, CONSTRAINT "PK_2e3cd3325f853089044baca6b77" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8e9c052ae338e0291158117938" ON "assistant_messages" ("conversationId") `);
        await queryRunner.query(`CREATE TABLE "assistant_conversations" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "adminUserId" integer NOT NULL, "title" character varying(100), CONSTRAINT "PK_ba3c0e4c991d8449c4c80dcc866" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_85453affdea1076576c1bdcd3d" ON "assistant_conversations" ("adminUserId") `);
        await queryRunner.query(`CREATE TABLE "user_roles" ("user_id" integer NOT NULL, "role_id" integer NOT NULL, CONSTRAINT "PK_23ed6f04fe43066df08379fd034" PRIMARY KEY ("user_id", "role_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_87b8888186ca9769c960e92687" ON "user_roles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b23c65e50a758245a33ee35fda" ON "user_roles" ("role_id") `);
        await queryRunner.query(`CREATE TABLE "product_tags" ("product_id" integer NOT NULL, "tag_id" integer NOT NULL, CONSTRAINT "PK_8ca809b37ff76596b63fe60ac41" PRIMARY KEY ("product_id", "tag_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5b0c6fc53c574299ecc7f9ee22" ON "product_tags" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f2cd3faf2e129a4c69c05a291e" ON "product_tags" ("tag_id") `);
        await queryRunner.query(`ALTER TABLE "wish_list_items" ADD CONSTRAINT "FK_a42daf2938b2aeec8ad000a9e47" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wish_list_items" ADD CONSTRAINT "FK_beb2bd75944954221278a59c763" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "settlements" ADD CONSTRAINT "FK_2a6aecc322b9c89e6b8f2c58341" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "settlements" ADD CONSTRAINT "FK_52e93e1b93923907c5493ea2024" FOREIGN KEY ("seller_id") REFERENCES "sellers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sellers" ADD CONSTRAINT "FK_83f4670f0e114d0be3731bade87" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_728447781a30bc3fcfe5c2f1cdf" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_9482e9567d8dcc2bc615981ef44" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_images" ADD CONSTRAINT "FK_b367708bf720c8dd62fc6833161" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_425ee27c69d6b8adc5d6475dcfe" FOREIGN KEY ("seller_id") REFERENCES "sellers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_9a5f6868c96e0069e699f33e124" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_summaries" ADD CONSTRAINT "FK_d05219e764bbdf7037198e26b92" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_145532db85752b29c57d2b7b1f1" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD CONSTRAINT "FK_e86fac2a18a75dcb82bfbb23f43" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD CONSTRAINT "FK_8ca96e53353b26ab5c48e0a92dd" FOREIGN KEY ("seller_id") REFERENCES "sellers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_a922b820eeef29ac1c6800e826a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_b2f7b823a21562eeca20e72b006" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inquiries" ADD CONSTRAINT "FK_a896a1864d60d5707403e0a0810" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inquiries" ADD CONSTRAINT "FK_fdb6fc620f190e9d51cb2c6a58b" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inquiries" ADD CONSTRAINT "FK_c860a531fd90a7697efabf4efa8" FOREIGN KEY ("seller_id") REFERENCES "sellers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_88cea2dc9c31951d06437879b40" FOREIGN KEY ("parent_id") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_6385a745d9e12a89b859bb25623" FOREIGN KEY ("cart_id") REFERENCES "carts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_30e89257a105eab7648a35c7fce" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carts" ADD CONSTRAINT "FK_2ec1c94a977b940d85a4f498aea" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assistant_messages" ADD CONSTRAINT "FK_8e9c052ae338e02911581179386" FOREIGN KEY ("conversationId") REFERENCES "assistant_conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "product_tags" ADD CONSTRAINT "FK_5b0c6fc53c574299ecc7f9ee22e" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "product_tags" ADD CONSTRAINT "FK_f2cd3faf2e129a4c69c05a291e8" FOREIGN KEY ("tag_id") REFERENCES "tags"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "product_tags" DROP CONSTRAINT "FK_f2cd3faf2e129a4c69c05a291e8"`);
        await queryRunner.query(`ALTER TABLE "product_tags" DROP CONSTRAINT "FK_5b0c6fc53c574299ecc7f9ee22e"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "assistant_messages" DROP CONSTRAINT "FK_8e9c052ae338e02911581179386"`);
        await queryRunner.query(`ALTER TABLE "carts" DROP CONSTRAINT "FK_2ec1c94a977b940d85a4f498aea"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_30e89257a105eab7648a35c7fce"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_6385a745d9e12a89b859bb25623"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_88cea2dc9c31951d06437879b40"`);
        await queryRunner.query(`ALTER TABLE "inquiries" DROP CONSTRAINT "FK_c860a531fd90a7697efabf4efa8"`);
        await queryRunner.query(`ALTER TABLE "inquiries" DROP CONSTRAINT "FK_fdb6fc620f190e9d51cb2c6a58b"`);
        await queryRunner.query(`ALTER TABLE "inquiries" DROP CONSTRAINT "FK_a896a1864d60d5707403e0a0810"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_b2f7b823a21562eeca20e72b006"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_a922b820eeef29ac1c6800e826a"`);
        await queryRunner.query(`ALTER TABLE "shipments" DROP CONSTRAINT "FK_8ca96e53353b26ab5c48e0a92dd"`);
        await queryRunner.query(`ALTER TABLE "shipments" DROP CONSTRAINT "FK_e86fac2a18a75dcb82bfbb23f43"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_145532db85752b29c57d2b7b1f1"`);
        await queryRunner.query(`ALTER TABLE "product_summaries" DROP CONSTRAINT "FK_d05219e764bbdf7037198e26b92"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_9a5f6868c96e0069e699f33e124"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_425ee27c69d6b8adc5d6475dcfe"`);
        await queryRunner.query(`ALTER TABLE "product_images" DROP CONSTRAINT "FK_b367708bf720c8dd62fc6833161"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_9482e9567d8dcc2bc615981ef44"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_728447781a30bc3fcfe5c2f1cdf"`);
        await queryRunner.query(`ALTER TABLE "sellers" DROP CONSTRAINT "FK_83f4670f0e114d0be3731bade87"`);
        await queryRunner.query(`ALTER TABLE "settlements" DROP CONSTRAINT "FK_52e93e1b93923907c5493ea2024"`);
        await queryRunner.query(`ALTER TABLE "settlements" DROP CONSTRAINT "FK_2a6aecc322b9c89e6b8f2c58341"`);
        await queryRunner.query(`ALTER TABLE "wish_list_items" DROP CONSTRAINT "FK_beb2bd75944954221278a59c763"`);
        await queryRunner.query(`ALTER TABLE "wish_list_items" DROP CONSTRAINT "FK_a42daf2938b2aeec8ad000a9e47"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f2cd3faf2e129a4c69c05a291e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5b0c6fc53c574299ecc7f9ee22"`);
        await queryRunner.query(`DROP TABLE "product_tags"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b23c65e50a758245a33ee35fda"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87b8888186ca9769c960e92687"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85453affdea1076576c1bdcd3d"`);
        await queryRunner.query(`DROP TABLE "assistant_conversations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8e9c052ae338e0291158117938"`);
        await queryRunner.query(`DROP TABLE "assistant_messages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_99e589da8f9e9326ee0d01a028"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0ec936941eb8556fcd7a1f0eae"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e59cfb4ce9deac3c9411eaa0e0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_56b91d98f71e3d1b649ed6e9f3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_610102b60fea1455310ccd299d"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "carts"`);
        await queryRunner.query(`DROP TABLE "cart_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_420d9f679d41281f282f5bc7d0"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c860a531fd90a7697efabf4efa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fdb6fc620f190e9d51cb2c6a58"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a896a1864d60d5707403e0a081"`);
        await queryRunner.query(`DROP TABLE "inquiries"`);
        await queryRunner.query(`DROP TYPE "public"."inquiries_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_11b604779919afa0aca3556c63"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_86f2b15ca0fd4f9a7eaae75fe6"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_75eba1c6b1a66b09f2a97e6927"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
        await queryRunner.query(`DROP TABLE "shipments"`);
        await queryRunner.query(`DROP TYPE "public"."shipments_status_enum"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d05219e764bbdf7037198e26b9"`);
        await queryRunner.query(`DROP TABLE "product_summaries"`);
        await queryRunner.query(`DROP TYPE "public"."product_summaries_status_enum"`);
        await queryRunner.query(`DROP TABLE "tags"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TYPE "public"."products_sales_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."products_approval_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."products_status_enum"`);
        await queryRunner.query(`DROP TABLE "product_images"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9482e9567d8dcc2bc615981ef4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_728447781a30bc3fcfe5c2f1cd"`);
        await queryRunner.query(`DROP TABLE "reviews"`);
        await queryRunner.query(`DROP TABLE "sellers"`);
        await queryRunner.query(`DROP TYPE "public"."sellers_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_068dd3735fbbc98234abb78375"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_52e93e1b93923907c5493ea202"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2a6aecc322b9c89e6b8f2c5834"`);
        await queryRunner.query(`DROP TABLE "settlements"`);
        await queryRunner.query(`DROP TYPE "public"."settlements_status_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TYPE "public"."roles_name_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a42daf2938b2aeec8ad000a9e4"`);
        await queryRunner.query(`DROP TABLE "wish_list_items"`);
    }

}
